version: "3"

services:
  front-end:
    build: ./frontend
    ports: 
      - "8080:3000"
  post-database:
    image: postgres
    restart: always
    env_file:
      - postService/.env
    expose:
      - 5481
    volumes:
      - post-data:/var/lib/postgresql/post
    command: -p 5481
  post-service:
    build: ./postService
    ports: 
      - "8081:8081"
    depends_on:
      - "post-database"
  comment-database:
    image: postgres
    restart: always
    env_file:
      - commentService/.env
    expose:
      - 5482
    volumes:
      - comment-data:/var/lib/postgresql/comment
    command: -p 5482
  comment-service:
    build: ./commentService
    ports: 
      - "8082:8082"
    depends_on:
      - "comment-database"
  user-database:
    image: postgres
    restart: always
    env_file:
      - userService/.env
    expose:
      - 5483
    volumes:
      - user-data:/var/lib/postgresql/user
    command: -p 5483
  user-service:
    build: ./userService
    ports: 
      - "8083:8083"
    depends_on:
      - "user-database"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

volumes:
    post-data:
    comment-data:
    user-data:
    pgadmin:
